services:
  instance:
    image: marketplace.gcr.io/google/debian11:latest
    networks:
      - elastic
    expose:
      - 80
      - 8080
    volumes:
      - .:/app/
networks:
  elastic:
    driver: bridge
